encounters = [
  {
      encounter_date: Date::strptime("2019-01-05"),
      sequence: 5,
      encounter_number: 01,
      start_time: "15:10",
      end_time: "16:05",
      vessel: "Morning Star",
      observers: "Melisa Pinnow, Jane Cogan, Tom Cogan",
      pods: "Transients",
      location_description: "Haro Strait",
      start_lat: "48 30.6",
      start_long: "-123 14.6",
      end_lat: "48 27.7",
      end_long: "-123 14.9",
      summary: "Melisa, Tom, and Jane met at Snug Harbor and left the dock at 1300 aboard “Morning Star”. “Morning Star” searched for whales around Spieden and Waldron Islands until a report came in at 1350 of two male killer whales heading north in Haro Strait toward Kelp Reefs. “Morning Star” headed to Haro Strait and stopped to scan near the Kelp Reefs area. With no whales in sight, “Morning Star” slowly headed south. At 1435, an update came in that the whales were in line between Ten Mile Point and Henry Island. “Morning Star” was right in the zone and spotted the whales about a mile away at 1510.\n\nIt was T93 and T97 and they were a few miles east of Cordova Bay/Gordon Head area. The two males were milling about on an apparent kill. Gulls flew in for scraps and the smell of oil was in the air. Once they were finished with their meal, T93 and T97 turned and slowly headed south, about two miles off of Ten Mile Point. The two stayed tight together for much of the time, but did split for a brief period towards the end of the encounter. The encounter was ended at 1605 as the two whales continued south toward Baynes Channel, about 0.75 miles north of the northern entrance to the channel."
    },
    {
      encounter_date: Date::strptime("2019-01-11"),
      sequence: 5,
      encounter_number: 02,
      start_time: "09:30",
      end_time: "14:30",
      vessel: "Morning Star",
      observers: "Dave Ellifrit, Melisa Pinnow, Jane Cogan, Tom Cogan",
      pods: " J, K, and L pod",
      location_description: "Strait of Juan de Fuca",
      start_lat: "48 09.45",
      start_long: "-122 44.67",
      end_lat: "48 19.20",
      end_long: "-123 21.40​",
      summary: "Dave, Melisa, Tom, and Jane met at Snug Harbor and left the dock at 0745 aboard “Morning Star”. The goal was to find L pod. Both K and L pod were seen in Puget Sound the previous day and L pod was of particular interest because there appeared to be a new calf. “Morning Star” headed straight to Admiralty Inlet. Not long after, J pod was seen heading toward Discovery Island/Constance Bank area from the west side of San Juan Island.\n\n“Morning Star” spotted blows at the northern end of Admiralty Inlet at 0930, about a mile northeast of Point Wilson. It was all of K pod sleepily traveling northwest in a tight group. Everyone was accounted for, including K25. K25 remains thin, but it appears that his condition has not worsened.\n\nIt wasn’t long until more blows were seen a few hundred yards behind K pod. It was all of L pod grouped up and also slowly heading northwest. “Morning Star” moved from K pod to L pod to find the new calf. All of L pod was accounted for and L77’s new calf, L124, was confirmed at 0950. The calf appeared to be about 3 weeks old and was bouncing around between L25, L41, L77 L85, and L119. A gender was not revealed during the encounter but there will hopefully be more opportunities in the future.\n\nMultiple social groups formed in L pod and many of the males, both young and old, were especially playful. As L pod exited Admiralty Inlet, even more whales became surface active with tail slaps, pec slaps, cartwheels, breaches, and spy hops. Up ahead, K pod had already exited the inlet and was still heading northwest.\n\nBy 1030, L pod was 1/3 mile due south of the SA buoy, still heading northwest but had increased their speed to 4-5 knots. K pod remained in a tight group to the west of L pod. Once southeast of Hein Bank, L pod began to disperse into smaller groups and picked their speed up to 6-7 knots. As the Ls were spreading out to the east, some the whales, especially the L4s and L47s, became surface active again. K pod also became surface active off to the west. It was clear that K and L pod could hear J pod and were eager to join them. “Morning Star” stayed with some of the L12s and L54s, but the L54s were not in such a hurry and fell behind.\n\nThe new calf kept up well with L25, L41, L77, and L119 as they sped northwest. “Morning Star” then decided to see where K pod went off to and re-acquired almost all of K pod in a tight group at 1310, southeast of Constance Bank. Then, news came in from whale watching boats that J pod was up ahead. K pod became surface active again as they closed the gap between them and J pod. Up ahead, some of Ls, including the L12s, had already reached J pod and were beginning to socialize. K pod arrived on scene soon after and joined the social groups that were forming.\n\nIt appeared the all of J pod was around and J17 was seen a few times, though a health shot was not acquired. If all of J pod was indeed there, than all 75 of the endangered southern resident orcas were in the same area together. “Morning Star” moved around the spread out social groups and found some trailing whales that were a little late to the party. Some of the L4s, the L72s, L47s, and the L54s slowly headed toward J, K, and the rest of L pod. The encounter was ended at 1430 near Constance Bank as the last two trailers, L88 and L117, continued toward the gathering."
    },
    {
      encounter_date: Date::strptime("2019-01-12"),
      sequence: 1,
      encounter_number: 03,
      start_time: "15:30",
      end_time: "16:15",
      vessel: "Orcinus",
      observers: "Dave Ellifrit",
      pods: "K pod",
      location_description: "Juan de Fuca Strait",
      start_lat: "48 22.39",
      start_long: "-123 19.48",
      end_lat: "48 21.17",
      end_long: "-123 23.36​",
      summary: "Ken called Dave at home in the early afternoon to report that he was seeing whales heading south a little north of Beaumont Shoal. Since the whales were reported to be K pod, Dave grabbed his gear, headed for Snug Harbor, and left in “Orcinus” at 1455. Dave arrived on scene about a half mile south of Trial Island at 1530. The whales were very spread out and traveling slowly west. K21 and the K20s were the first whales encountered and seemed to be the most northerly and westerly of the whales. Since there was not much daylight left and the whales were so spread out, the priority was to find K25 and document how he was doing health-wise.\nAfter looking all over, and seeing a few more spread out whales like the K27s, Dave was able to get on K25 with the help of “Strong Tide” who re-found him and called Dave over. Upon approach, K25 surfaced from a very long, long dive and seemed to be foraging. He soon straightened out and headed west-surfacing many times in a row, cooperatively, and Dave was able to get the shots he needed before it was time to leave due to failing light. The encounter ended with K25 heading west south of the Victoria waterfront at 1615. While K25 did not look 100% healthy, neither did it look like his health worsened much since we last received really good photos of him from October 12th. It is too early to say whether he will survive this latest health scare but it is encouraging that he has not deteriorated further since looking pretty bad back in September and may have actually improved some.\nMany thanks to “Strong Tide” for helping \"Orcinus\" get on the whales and finding K25.​Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-01-14"),
      sequence: 1,
      encounter_number: 04,
      start_time: "11:40",
      end_time: "12:55",
      vessel: "Orcinus",
      observers: "Dave Ellifrit, Melisa Pinnow",
      pods: "Transients",
      location_description: "Haro Strait",
      start_lat: "48 24.284",
      start_long: "-123 11.98",
      end_lat: "48 38.23",
      end_long: "-123 10.52​",
      summary: " Dave and Melisa were at the Center for Whale Research when a small group of killer whales appeared out front at 1120. Binoculars revealed that they were the T18s so Dave and Melisa quickly headed to Snug Harbor and left the dock at 1136 aboard “Orcinus”. “Orcinus” arrived on scene with the T18s at 1140. The whales were in a tight group as they slowly traveled north in Haro Strait and past the mouth of Mitchell Bay. The four whales then split into pairs as they headed toward Kellett Bluff. T19 and T19B took the lead while T18 and T19C trailed behind. The whales rounded Kellett and were about ¾ of a mile south of Batttleship Island by 1219. They swam between Battleship and Henry Island in their pairs and then formed a tight group again once they were in Spieden Channel. No obvious kills were observed. The encounter was ended at 1255 as the whales passed Danger Shoal, aiming for Sentinel Island.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-01-25"),
      sequence: 1,
      encounter_number: 5,
      start_time: "14:03",
      end_time: "15:42",
      vessel: "Mike 1",
      observers: "Mark Malleson",
      pods: "Bigg's Transients",
      location_description: "South of Constance Bank",
      start_lat: "48 17.3",
      start_long: "-123 18.5",
      end_lat: "48 19.7",
      end_long: "-123 29.3​",
      summary: "I received a report from Spencer Domico at ~1300 that he had come across westbound killer whales 11 miles south of Discovery as he was headed to Port Angeles.\nI left Victoria harbour on Mike 1 at 1330 as Spencer left the T085's at 48 16/123 17.8 traveling north. I re-spotted them at 1403 chasing a harbour porpoise (48 17.3/123 18.5). They caught it and consumed it within 2 minutes of me arriving.\nThey traveled northwest to the southwest corner of Constance Bank and then turned to the west. They were traveling west towards Pedder Bay at a steady 5 knots and doing ~6-minute dives. I watched them pass by a couple of harbour seals and did not observe any more predation. I ended the encounter at 1542 and returned to Victoria harbour.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-01-30"),
      sequence: 1,
      encounter_number: 06,
      start_time: "11:25",
      end_time: "14:15",
      vessel: "Orcinus and Morning Star",
      observers: "Dave Ellifrit, Kelley Balcomb-Bartok on Orcinus, Melisa Pinnow, Tom and Jane Cogan on Morning Star",
      pods: "L pod",
      location_description: "Canadian side of Haro Strait and Juan de Fuca Strait",
      start_lat: "48 30.59",
      start_long: "-123 13.33",
      end_lat: "48 22.48",
      end_long: "-123 22.36​",
      summary: "Jane Cogan called Dave at home to report that she was hearing resident calls on her hydrophone. Dave then called Kelley and they met at Snug Harbor and left in the boat around 1115. Jane had called again to say the whales were heading south way over on the Canadian side of Haro Strait so we headed southwest and around a freighter to where they ought to be.\nWe saw our first whale at 1125 about a mile or so south of Kelp Reef. The whales were extremely spread out over the Canadian side of the strait and we only saw a few individuals and one small group. All the whales we could see were heading southerly toward Beaumont Shoal and Seabird Point on Discovery Island. The first whale we saw was L115 before we moved to a distant small group that included L72, L105, L90, and L103. So, we had at least the group of 18 L pod whales that included the L4, L47, and L72 matrilines plus L90. Since the other whales were so sparse and hard to find, plus the lack of any males larger than L105, it made us suspect that these 18 Ls were the only residents here. Most of the whales were taking long dives and a few distant individuals looked like they could be foraging.\nA little after we left the group of four, we found L83 and L110 but other whales were still just singles in the distance until we started to approach Seabird Point. As we had expected, the distant animals started to funnel together as they approached Seabird Point around 1245. All the other L4s appeared along with our L72s, L90, and L103 group. As the whales rounded Seabird Point, they turned southwest and traveled toward Trial Island in several small groups. Other than a small tight group of L4s, the whales began to spread out again as they crossed the Oak Bay flats. By this point in the encounter, we had seen 15 of the 18 whales we had expected to see that day and suspected that the three we were missing (L47, L91, and L122) were well to the south of us. The Cogans came out in their boat “Morning Star” with Melisa aboard and we sent them to look to the south for our last three whales. They soon called to say that they did indeed find the remaining L47s that we hadn’t seen yet. From the look of it, the L47s were a good three to four miles south of the more northerly whales we were with. The whales were still heading west when we ended the encounter at 1415 off the Victoria waterfront.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388and Be Whale Wise Guidelines"
    },
    {
      encounter_date: Date::strptime("2019-01-31"),
      sequence: 1,
      encounter_number: 07,
      start_time: "09:26",
      end_time: "11:11",
      vessel: "Mike 1",
      observers: "Mark Malleson, Hanna Magnusson",
      pods: "Bigg's Transients",
      location_description: "Zero Rock",
      start_lat: "48 29.6",
      start_long: "-123 16.4",
      end_lat: "48 35.3",
      end_long: "-123 19.1​",
      summary: "I spotted a group of killer whales near the Chain Islands from the living room window traveling north through Oak Bay at ~0820. Hanna and I got organized and headed downtown to mobilize Mike 1. We departed the dock at 0900 and made our way north towards Zero Rock. We stopped to have a scan slightly north of Baynes Channel and I could see them a little south of Zero Rock pointed north.\nWe started the encounter at 0926 (48 29.6/123 16.4) with T060 and T010C who were traveling a few hundred hards behind the rest of the group.\nAt 0934 the lead group went into a bait ball and grabbed a seal as the 2 bulls picked up the pace to join them for some prey sharing (48 30.2/123 16.7).\nThe group turned slightly west towards Little Zero Rock and milled about for a couple of minutes before separating into 2 groups. T060C and T060E took turns keeping tabs on a seal hiding out on the bottom for ~20 minutes before they grabbed it and shared it at the surface at 1033 (48 32.3/123 19.3). They didn't waste any time eating it and then porpoised at 10 knots towards Darcy Island to catch up with the other 3 members of the group. They reunited at 1048 (48 33.8/123 19. 7) and continued north towards Sidney Channel. At 1100 they made another seal kill at 48 34.5/123 18.8.\nWe ended the encounter at 1109 as they entered Sidney Channel (48 35.3/123 19.1) T060E was trailing by ~200 metres.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-01-31"),
      sequence: 1,
      encounter_number: 08,
      start_time: "12:52",
      end_time: "15:04",
      vessel: "Mike 1",
      observers: "Mark Malleson",
      pods: "Bigg's Transients",
      location_description: "William Head",
      start_lat: "48 21.1",
      start_long: "-123 28.1",
      end_lat: "48 17.8",
      end_long: "-123 34.4​",
      summary: "When we returned to Victoria harbour at ~1200 after our morning encounter with the T010's and the 3 members of the T060's I received a report o of a pair of bulls seen east bound in Race Passage at 1054.\nI dropped off Hanna and headed back out on my own to look for them.\nI came across the T046's with T122 at 1252 between Albert Head and William Head (48 21.1/123 28.1) traveling north. Within a few minutes they turned around and worked their way back towards Race Passage. They were doing long dives between breath sequences of ~6 minutes and appeared to be resting. They milled about west of Race Rocks (48 17.8/123 34.4) as if they were stalking a prey item but I did not confirm a kill. I ended the encounter at 1504 at this location as they continued slowly west bound south of Church Rock.Photos taken under Federal PermitsNMFS PERMIT: 15569-01/ DFO SARA 388Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-02-10"),
      sequence: 1,
      encounter_number: 09,
      start_time: "12:18",
      end_time: "12:48",
      vessel: "Mike 1",
      observers: "Mark Malleson, Duncan Stamper, Steve Isbister, Chris Vesalo",
      pods: "Bigg's Transients",
      location_description: "East Sooke",
      start_lat: "48 18.3",
      start_long: "-123 38.9",
      end_lat: "48 17.8",
      end_long: "-123 36.5",
      summary: "I decided to head out on Mike 1 with the sailing crew when no one showed up to race against for Sunday's \"Around the Buoys\" at the yacht club due to the frigid temperatures. I had received a report from Jane Cogan that she had heard loud transient calls on the hydrophone at 0600 as well as hearing a report of 3 killer whales southbound past Eagle Point at 0715.\nWe had a quick look from Gonzales lookout before heading to the boat. With a large ebb and strong south east winds forecasted for the afternoon we decided to head west towards Race Rocks leaving Victoria's harbour at 1145. After a brief stop at Race Rocks to check out the sea lions, harbour seals and elephant seals we continued west a couple miles offshore. At 1218 as we were approaching Bechey Head I spotted a bull dorsal fin what appeared to be coming straight at us. We stopped and waited while I scanned in case they were going away form us and then T100 E and T100F popped up close to us east bound (48 18.3/123 38.9). We tracked them them for ~ 30 minutes while they travelled east. No predation was observed for our encounter. We left them at 1248 slightly offshore of Becher Bay (48 17.8/123 36.5)Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-02-16"),
      sequence: 1,
      encounter_number: 10,
      start_time: "09:42",
      end_time: "10:15",
      vessel: "Mike 1",
      observers: "Mark Malleson, Hanna Magnusson",
      pods: "Bigg's Transients",
      location_description: "Zero Rock",
      start_lat: "48 30.9",
      start_long: "-123 17.5",
      end_lat: "48 32.5",
      end_long: "-123 19.6​",
      summary: "I received a call at 0826 from George Hamilton who spotted a group of ~ 7 killer whales slowly north bound past his place north of Ten Mile Point.\nHanna and I immediately headed downtown to mobilize Mike 1 and departed Victoria's harbour at 0900.\nAt 0942 I spotted a group of killer whales near Little Zero Rock through the binoculars. We approached the area slowly waiting for another sighting but it wasn't until well over 10 minutes before I spotted them again (48 30.9/123 17.5) They were doing between 10 and 14 minute dives the whole time we were there. T090 and T090D were slightly east of the rest of the T090's and the T069D's.\nWe ended the encounter at 1015 slightly north of Little Zero Rock (48 32.5/123 19.6) in order for me to get back to Victoria harbour to take guest out on a Prince of Whales 1100 departure. Our last distant looks showed they were pointed north towards James Island.\nAfter well over 2 hours of scanning and searching the area I re sighted them at 1315 very close to where we started our encounter in the morning. This time they were pointed very slowly south.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-02-18"),
      sequence: 1,
      encounter_number: 11,
      start_time: "14:54",
      end_time: "16:31",
      vessel: "Orcinus",
      observers: "Dave Ellifrit, Melisa Pinnow",
      pods: "J pod",
      location_description: "Patos Island",
      start_lat: "48 47.020",
      start_long: "-123 00.794",
      end_lat: "48 46.122",
      end_long: "-122 55.517​",
      summary: "At 1323, a whale watching boat reported that they had found members of J pod near East Point, Saturna Island. Dave and Melisa headed to Snug Harbor and left the dock at 1415 aboard “Orcinus”. At 1454, “Orcinus” arrived on scene with the J16s about three-quarters of a mile west of the Patos Island lighthouse. J16, J36, and J42 were traveling east tight together. J26 was paralleling them a few hundred yards to the north and swam over to join them soon after.\n\nTo the north, the rest of J pod was spread out but slowly coming together into social groups as they also headed east. At 1538, “Orincus” left the J16s as they took the southern side of Patos Island and headed over to the rest of the pod, which took the northern side. The largest of the social groups was made up of J19, J22, J37, J38, J41, and J49. They were less than a quarter of a mile from the Patos shoreline and were surface active with occasional tail slaps, pec slaps, and spy hops. It wasn’t long until J27, J31, and J39 joined the larger group from further inshore. Goofing off and trailing slightly behind were J40, J45, and J51.\n\nJ40, J45, and J51 caught up with the larger group (which now contained all of the J11s, J14s, J19s, and J22s) as it neared Toe Point and many of the whales became more surface active with frequent tail slaps, inverted tail slaps, and pec slaps. At 1605, the J11s, J14s, J19s, and J22s cleared Patos Island and continued east toward Lummi Island. The J16s had also cleared Patos by this time and could be seen in the distance to the south, also aiming toward Lummi.\n\nAt 1618, the J16s joined the J11s, J14s, J19s, and J22s and they all turned south toward President Channel, though they seemed a bit indecisive about it at first. The encounter was ended at 1631 as the whales slowly swam south along the Sucia Island shoreline toward Present Channel. The J17s and L87 were not present during the encounter so the CWR will wait for another J pod encounter to confirm how J17 is fairing.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-02-23"),
      sequence: 1,
      encounter_number: 12,
      start_time: "16:10",
      end_time: "17:05",
      vessel: "Orcinus and Tonto",
      observers: "Dave Ellifrit on Orcinus and Ken Balcomb on Tonto",
      pods: "J pod",
      location_description: "Haro Strait",
      start_lat: "48 34.11",
      start_long: "-123 12.45",
      end_lat: "48 36.41",
      end_long: "-123 15.90",
      summary: "Jane Cogan called Dave at home around 1425 to report that she was hearing a single repeated call on the Lime Kiln hydrophone. She then called back a half hour later to relay a report that whales had been seen heading north near Lime Kiln. Dave grabbed his stuff and headed first to the County Park to take a look from shore. At least one whale was seen way offshore of the park and “Sea Lion” came from the north and slowed down for something offshore of CWR. Jeanne Hyde reported seeing a small group of whales to the southwest of the leaders. Dave then headed on to Snug Harbor and left in the boat around 1550.\nAs “Orcinus” putted out of the harbor, “Sea Lion” was seen nearing Kellett Bluff and Ken was also out in “Tonto”. “Orcinus” headed southwest out of Mitchell Bay to try to find the group Jeanne had seen. Jane called on the radio to report that the three whales who had passed her place were the J19s and that was who was probably near Kellett Bluff. After about 20 minutes of searching, Dave finally saw his first whale mid-strait off Mitchell Bay. This was J39 who foraged a little before passing the boat and continuing north. There were no other whales in sight so “Orcinus” headed in the direction of Kelp Reef. After another fifteen minutes, a small group was seen about three quarters of a mile to the north of Kelp Reef. This was J16, J36, J42, and J31 traveling in a group together. At least two males and a possible third whale could now be seen spread back across the strait off the south end of Mitchell Bay. All the whales were taking extremely long dives and were easy to miss when they finally came up again. Dave overshot the nearest male who was at least a half mile to the southeast of the small group and went to see the far male instead. This was J27 and he was foraging about a mile off Kellett Bluff. The other male seen earlier was seen again well to the west off the southeast end of Sydney Island. This was J26 and the encounter ended at 1705 with him heading north about a half mile east of Halibut Island.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-03-07"),
      sequence: 1,
      encounter_number: 13,
      start_time: "11:07",
      end_time: "13:07",
      vessel: "Mike 1",
      observers: "Mark Malleson, Hanna Magnusson",
      pods: "Bigg's",
      location_description: "Victoria's waterfront",
      start_lat: "48 23.9",
      start_long: "-123 27.0",
      end_lat: "48 24.3",
      end_long: "-123 18.7",
      summary: "I received a report a group from a colleague on a tugboat who saw a group of killer whales between Albert Head and William Head a mile offshore travelling north east. Hanna and I mobilized Mike 1 and left Victoria harbour at 1045. We spotted them at 1107 slightly north east of Albert Head moving very slowly towards Victoria's harbour mouth. They were doing close to 7 minute dives and making less than 2 knots, likely resting. After ~ 30 minutes they picked up the pace to close to 6 knots after crossing a tide line and worked their way past Clover Point within a hundred metres of shore. They milled about for less than a minute offshore of Harling Point before continuing on towards Enterprise channel. We left them at 1307 as a couple of commercial whale watch boats arrived. We did not observe any predation for the 2 hour encounter.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-03-09"),
      sequence: 1,
      encounter_number: 14,
      start_time: "15:03",
      end_time: "16:30",
      vessel: "Orcinus",
      observers: "Dave Ellifrit, Melisa Pinnow",
      pods: "Transients",
      location_description: "Rosario Strait",
      start_lat: "48 35.050",
      start_long: "-122 83.456",
      end_lat: "48 37.196",
      end_long: "-122 44.596​",
      summary: "At about 1138, a report came in of transient killer whales eastbound off the south end of Shaw Island. At about 1200, another group of transients was found entering Thatcher Pass from Rosario Strait. Dave and Melisa waited a bit to see which routes the whales would take and within a few hours, the two groups came together in Upright Channel.\n\nDave and Melisa headed to Snug Harbor and left the dock at 1430 aboard “Orcinus”. At 1503, “Orcinus” arrived on scene with the T123s and T124As off of Foster Point, near the east entrance of Harney Channel. The whales were all grouped up and zig-zagging their way toward Obstruction Pass. Surfacing beside T124A3 was a new calf, likely born at the beginning of 2019. T123’s calf that was born in late 2018 was also present.\n\nAt 1541, the whales swam through Obstruction Pass and entered Rosario Strait. Once in Rosario, the T123s and T124As zig-zagged their way northwest. The encounter was ended at 1630 as the whales made a turn to the north, just south of Peapod Rocks. No kills were observed during the encounter.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date:"Date::strptime(2019-03-13"),
      sequence:1,
      encounter_number:15,
      start_time: "15:30",
      end_time: "17:45",
      vessel: "Orcinus",
      observers: "Dave Ellifrit and Katie Jones",
      pods: "Transients",
      location_description: "Spieden Channel",
      start_lat: "48 38.30",
      start_long: "-123 08.16",
      end_lat: "48 38.58",
      end_long: "-123 11.20​",
      summary: "After a series of phone calls from Jane Cogan relaying reports of a group of transients heading up San Juan Channel, Dave and Katie met at Snug Harbor and left in the boat a little after 1500. We arrived on scene at about 1530 in Spieden Channel. The whales, already identified as the T90s and T101s, were traveling slowly west near the southeastern shoreline of Spieden Island. Most of the whales were in one tight group with T101A being the lone outlier traveling a couple of hundred yards ahead of the others. The whales moved a little offshore as they moved west. When they were adjacent to Sentinel Island, they began to wake up and T101B did a big belly flop which he followed with a half breach.\nSoon after, the whales started to loosen up and began feeding on something. They may have made an inconspicuous kill then but there is also chance that the whales had killed a sea lion prior to our arrival and were carrying it for most of the way through Spieden Channel before feeding upon it. We never did get a good look at what they killed but the whales were feeding and socializing in the same area around the west end of Spieden Island for over an hour and a half. Since the whales weren’t going anywhere, much of the encounter was spent with the engine off while the whales milled around. We did photo T102 with two big whiskers coming up from the other side of his head so we know they got at least one large pinniped. T101A and T101B were hanging out together around the periphery of the group with occasional forays into the middle of the action. At one point, the two brothers were seen with a large chunk of something while the other whales were feeding on something else a short distance away. Throughout the encounter there were lots of taillobs and other percussive behavior. T90C breached several times and, later in the encounter, was spyhopping repeatedly. Towards the end, the whales were socializing and acting quite confident. We ended the encounter at 1745 off the west end of Spieden Island with the T90s and T101s beginning to move northwest toward Stuart Island.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388Video taken under Be Whale Wise Guidelines"
    },
    {
      encounter_date: Date::strptime("2019-03-14"),
      sequence: 1,
      encounter_number: 16,
      start_time: "12:20",
      end_time: "16:10",
      vessel: "Orcinus",
      observers: "Dave Ellifrit",
      pods: "Transients",
      location_description: "Swanson Channel and Boundary Pass",
      start_lat: "48 43.90",
      start_long: "-123 17.72",
      end_lat: "48 44.23",
      end_long: "-123 09.16​",
      summary: "Tom Cogan called Dave late morning to report that they were hearing whales on the hydrophone. After spotting them, the Cogans went out on their boat “Morning Star” with Melisa Pinnow aboard and called again to say that they had identified the whales as the T10s and T2Cs and that they were heading north near Gooch Island. Dave grabbed his gear, headed for the boat, and left Snug Harbor a little before noon.\n“Orcinus” arrived on scene around 1220 where the T10s and the T2Cs, minus T2C2 and T2C3, were traveling slowly north tight to the east shoreline of Moresby Island. Several whales from this group stopped and briefly logged at the surface. After a long dive, the whales moved more into the middle of lower Swanson Channel and began to wake up a bit. T10 did two big cartwheels and T2C did one. A whale appeared from the north and this turned out to be T2C3. T2C3 logged briefly at the surface about a quarter of a mile north of the other whales when all the whales went on another long dive. When the whales came up again, T2C3 had re-joined the group and everybody continued north.\n“Morning Star” had left the scene a while ago and had gone on a whale search up Boundary Pass toward East Point. A bit before 1300, they found the T49As near East Point heading quickly southwest down Boundary Pass. “Orcinus” left the T2Cs and T10s at about 1310 in mid-Swanson Channel to head over to where the T49As were in Boundary Pass, arriving on scene mid-way between Blunden Island and Johns Pass twenty minutes later. South of South Pender Island, the whales turned west with T49A1 about a half mile to the south of the other T49As. All the T49As were traveling fast and T49A1 was on a converging course with the others. T49A1 joined the rest of the T49As by the time they turned north at the south end of Swanson Channel.\nBy this time, we had heard that the T2Cs and T10s had turned around and were heading south again in Swanson Channel. At 1400, the T49As had slowed down and were traveling in a tight group just a little north of Moresby Island. The T10s and T2Cs were briefly seen logging at the surface north of the T49As off Mouat Point before they went on a long dive. Suddenly four or five new whales appeared heading south about three quarters of a mile north of the T49As and then all the whales went on a long dive. After an extremely long long dive, all the whales came up a good distance away heading very quickly southeast toward the Pender Bluffs. Almost all the whales were in one single socializing group close in to the dark rocks of the bluff. T19B and T19C were identified so now we knew at least the T18s had joined up with the others. T2C2 also appeared well offshore of the others where he kept a low profile. The large group traveled along the rocks as they came down the bluffs, crossed the Bedwell Harbor entrance, and moved east along South Pender Island’s south shoreline. The T10s reappeared traveling almost a half mile behind the large group. T49A1 had moved offshore by himself and appeared to be foraging. T2C2 also showed up traveling slowly all by himself another quarter mile behind the T10s. The encounter ended at 1610 with the large group off the mouth of Plumper Sound and the other four whales still spread out behind them as they all headed slowly up Boundary Pass.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388Video taken under Be Whale Wise Guidelines"
    },
    {
      encounter_date: Date::strptime("2019-03-18"),
      sequence: 1,
      encounter_number: 17,
      start_time: "16:10",
      end_time: "16:45",
      vessel: "Morning Star",
      observers: "Melisa Pinnow, Jane Cogan, Tom Cogan",
      pods: "Transients",
      location_description: "Howe Sound",
      start_lat: "49 31.788",
      start_long: "-123 19.917",
      end_lat: "49 33.440",
      end_long: "-123 19.546",
      summary: "“Morning Star” was searching for whales in Georgia Strait when a report came in around 1345 of killer whales traveling toward Howe Sound from the east side of Bowen Island. “Morning Star” changed course and headed for Howe Sound. At 1610, T10C and T123A were spotted off the west side of Anvil Island. The two males were rolling around and goofing off together as they headed toward the northern tip of Anvil.\n\nAbout ten minutes later, T10 and the rest of the T123s were spotted grouped up and tucked in close to shore a few hundred yards ahead of the males. T10C and T123A almost caught up to the other whales as they passed the northern tip of Anvil Island. Once northeast of Anvil, everyone fanned out with T10, T10C, and T123A spread out and trailing behind T123, T123C, and T123D by a few hundred yards. The encounter was ended at 1645 as the whales and headed deeper into Howe Sound. No kills were observed during the encounter.Photos taken under Be Whale Wise Guidelines"
    },
    {
      encounter_date: Date::strptime("2019-03-18"),
      sequence: 2,
      encounter_number: 18,
      start_time: "18:10",
      end_time: "18:35",
      vessel: "Morning Star",
      observers: "Melisa Pinnow, Jane Cogan, Tom Cogan",
      pods: "Transients",
      location_description: "Georgia Strait",
      start_lat: "48 54.095",
      start_long: "-123 17.939",
      end_lat: "48 50.972",
      end_long: "-123 13.079​",
      summary: "“Morning Star” had just finished Encounter 17 in Howe Sound and was crossing Georgia Strait to head back home. Upon was nearing the entrance to Active Pass, many blows were spotted to the south at 1810. “Morning Star” headed from Georgina Point over toward Edith Point to investigate.\n\nThe whales were spread out in small groups and quickly heading south. T102 was the first whale identified. T90B, T101A and T101B were also nearby. Inshore of them was the largest group which consisted of T90, T90C, T90D, T101, T124A, and T124A6. “Morning Star” moved between the groups for proof of presence shots and ended the encounter at 1835 as the whales continued south in the Strait of Georgia, off Georgeson Island.Photos taken under Be Whale Wise Guidelines"
    },
    {
      encounter_date: Date::strptime("2019-03-19"),
      sequence: 1,
      encounter_number: 19,
      start_time: "12:00",
      end_time: "13:35",
      vessel: "Morning Star",
      observers: "Melisa Pinnow, Jane Cogan, Tom Cogan",
      pods: "Transients",
      location_description: "Trincomali Channel",
      start_lat: "48 53.246",
      start_long: "-123 26.170",
      end_lat: "48 57.219",
      end_long: "-123 35.605​",
      summary: "With sunny skies and low winds in the forecast, “Morning Star” departed Snug Harbor at 1108 in search of killer whales. At 1120, a whale watching boat found whales heading west in Trincomali Channel. “Morning Star” headed that way and arrived on scene west of Parker Island at 1200. The first whale encountered was T2C2, who has severe scoliosis. He was slowly heading north and trailing behind the rest of the whales by 3/4 of a mile. “Morning Star” took a few proof of presence shots of T2C2 before heading to the northern whales.\n\nThe other whales turned out to be the rest of T2C2’s family and the T123s. They were quickly moving north (7-9 knots) west of Wise Island. Males T2C1 and T123A were rolling around together while the rest of the two families were grouped up a few hundred yards to the north. “Morning Star” continued north to get photos of the remaining members of the T2Cs and T123s as they took the east side of Wallace Island. Occasionally, the T2Cs and T123s would pause and log at the surface for a few minutes. Perhaps they were waiting for T2C2 to catch up but he was still trailing far behind them.\n\nSuddenly, another group of whales appeared a few hundred yards to the west. It was the T49As in a resting line and “Morning Star” saw these whales briefly before they disappeared from view as they slowly headed north on the west side of Wallace Island. At 1255, “Morning Star” left the T2Cs and T123s to get better proof of presence shots of the T49As. The T49As had continued north through Houstoun Passage and were taking ten minute long deep dives. The encounter was ended at 1335 after the T49As went on a long dive off of Squthey Point at the north end of Saltspring Island.Photos taken under Be Whale Wise Guidelines"
    },
    {
      encounter_date: Date::strptime("2019-03-19"),
      sequence: 2,
      encounter_number: 20,
      start_time: "15:15",
      end_time: "16:30",
      vessel: "Morning Star",
      observers: "Melisa Pinnow, Jane Cogan, Tom Cogan",
      pods: "J pod",
      location_description: "Georgia Strait",
      start_lat: "49 04.390",
      start_long: "-123 34.070",
      end_lat: "48 59.771",
      end_long: "-123 28.069​",
      summary: "After ending Encounter 19 off the north end of Saltspring Island, “Morning Star” continued north through Dodd Narrows and into Georgia Strait to search for more killer whales. At 1500, a report came in of killer whales, possibly J pod, outside of Porlier Pass. Luckily, “Morning Star” was not too far away and arrived on scene at 15:15. The whales were spread out across Georgia Strait as they traveled south a few miles east of Valdes and Galiano Islands.\n\nThe first whale to be confirmed was J27 and he wasn’t in any hurry as he swam along. A few hundred yards to the east of him were J19 and J41, associating with each other occasionally and also in travel mode. To the east of them were J42 and J51 and they were more grouped up. At one point, J42 and J51 found a salmon and worked together to try to catch it. They may have caught it in the end but it was not entirely clear. J36 passed by J42 and J51 just before they had started foraging but quickly backtracked and joined up with them right after they had either caught the salmon or lost it.\n\nAt 1610, J16 and J26 was spotted foraging together to the east. Soon after, J31 and J39 were found near each other even further east. With no other whales in sight, the encounter was ended at 1630 as J pod slowly continued south in Georgia Strait, about half way from Porlier Pass to Active Pass.Photos taken under Be Whale Wise Guidelines"
    },
    {
      encounter_date: Date::strptime("2019-03-19"),
      sequence: 3,
      encounter_number: 21,
      start_time: "17:30",
      end_time: "18:50",
      vessel: "Morning Star",
      observers: "Melisa Pinnow, Jane Cogan, Tom Cogan",
      pods: "Transients",
      location_description: "President Channel",
      start_lat: "48 41.900",
      start_long: "-123 05.400",
      end_lat: "48 42.800",
      end_long: "-123 00.131​",
      summary: "After ending Encounter 20 in Georgia Strait at 1630, “Morning Star” headed to Boundary Pass to find more transient killer whales that had been sighted south of Patos Island earlier in the day. The whales were reported to still be in Boundary Pass and heading toward Sandy Point on Waldron Island at 1645. At 1730, “Morning Star” arrived on scene on the west side of Waldron Island. The whales were spread out in small groups and pointing southeast.\n\nThe T101s and others were seen off in the distance in Cowlitz Bay while two other groups were approaching White Rock. “Morning Star” headed to the White Rock groups when a small calf was spotted, then two! The first calf belonged to the T36As and had already been documented by Mark Malleson on a DFO research trip earlier in March. The other calf belonged to the T36Bs and was first observed in January.\n\nThe T36As and T36Bs paralleled each other by a few hundred yards as they passed White Rock and then quickly turned north into President Channel. The T36Bs moved closer to the Waldron Island shoreline while the T36As trailed slightly behind to the east. Up ahead, the T101s and others could be seen up against Waldron and quickly heading north. “Morning Star” moved north to investigate and found the T101s trailing a few hundred yards behind the T99s and T124A1. When T99s and T124A1 slowed down, the T101s moved offshore and passed them. The T36Bs then re-appeared a few hundred yards behind the T99s and T124A1. The encounter ended at 1850 as the three groups passed Mail Bay and pointed toward Paint Hammond.Notes-Comments:Photos taken under Be Whale Wise Guidelines"
    },
    {
      encounter_date: Date::strptime("2019-03-22"),
      sequence: 1,
      encounter_number: 22,
      start_time: "12:40",
      end_time: "15:03",
      vessel: "Orcinus",
      observers: "Dave Ellifrit, Melisa Pinnow",
      pods: "J pod",
      location_description: "Haro Strait",
      start_lat: "48 27.01",
      start_long: "-123 13.59",
      end_lat: "48 29.969",
      end_long: "-123 13.207",
      summary: "At about 1132, whale watching boats found J pod southbound in northern Haro Strait. Dave and Melisa headed to Snug Harbor and left the dock at 1230 aboard “Orcinus”. At 1240, “Orcinus” arrived on scene about two miles southeast of Mandarte Island. J pod was very spread out in small groups and still slowly heading south.\n\nJ37, J49, and L87 surfaced a few hundred yards south of “Orcinus” in a loose group. J22 and J38 were then spotted near each other about a quarter of a mile to the north. When blows were seen a few hundred yards to the northeast of J22 and J38 at 1300, “Orcinus” went to investigate. Amazingly, the blows came from J17 and J53! J17 was still alive and had even improved a little in body condition since December/January. However, her breath still smelled awful so the CWR will remain cautiously optimistic that she will survive.\n\nAs J17 and J53 approached Kellet Bluffs on Henry Island, “Orcinus” headed off to look for other whales. After a few repeat whales, more groups were found half a mile north of Kelp Reefs at 1352. The largest group was made up of the J19s, J31, the J35s, J40, and J46. J16, J36, and J42 paralleled the larger group a few hundred yards to the west and slightly trailing behind them were J26 and J27. As the whales slowly headed south past Kelp Reefs at 1428, J26 joined J16, J36, and J42 while J27 headed over to the larger group. The encounter ended at 1503 about two miles southeast of Kelp Reefs as the two groups slowly continued south toward Seabird Point on Discovery Island.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-03-26"),
      sequence: 1,
      encounter_number: 23,
      start_time: "12:30",
      end_time: "17:05",
      vessel: "Orcinus",
      observers: "Dave Ellifrit",
      pods: "J pod and L87",
      location_description: "Boundary Pass and San Juan Channel",
      start_lat: "48 41.54",
      start_long: "123 07.12",
      end_lat: "48 40.53",
      end_long: "123 07.27​",
      summary: "Ken called Dave at home in the late morning to relay a report that J pod had been found heading slowly down Boundary Pass. Dave grabbed his gear, headed to the boat, and left Snug Harbor around 1145ish. “Orcinus” got to the general area in Boundary Pass around 1215 but the whales were so spread out that it was 1230 before the first whales were seen and encountered.\nThe first group encountered was J36, J41, and J51 and they were about halfway between Blunden Island and Johns Pass. The threesome were socializing as they fast traveled east toward White Rock. About a half mile to the south of these three, J19 and J39 were paralleling each other-spread by about 200 yards-as they also fast traveled east. A male appeared way up ahead in the White Rocks area. This turned out to be J26. J27 also appeared another half mile east of J26 and both of them foraged separately in the area between White Rock and Flattop Island.\nMore whales were seen closer to the Orcas Island shoreline and this turned out to be the J17s, J22s and J40. This group was loosely stretched out as they turned southwest and then filed around the north and west shorelines of Jones Island. J17 herself was present with J53 beside her with the others near Jones Island. Most of the group began milling as they headed slowly southeast on the south side of Jones while J17 began traveling down San Juan Channel by herself a couple of hundred yards ahead of the others. J53 stayed to play with the group. J17 did not have bad breath when the research boat was near her on this day but that may have been a matter of wind direction. L87 and the J37s appeared as they also rounded Jones Island about a quarter mile behind the others and soon joined the milling whales.\nA single whale was seen a few hundred yards to the northwest of the Jones Island group and another group had formed just a little north of O’Neil Island. The single whale turned out to be J45 and he traveled slowly southeast mid-channel by himself until angling toward the whales near Jones Island. By 1445, the J17s, J22s, J14s, and L87 group were only about half a mile southeast of Jones Island before they had turned around and began heading slowly back to the northwest. “Orcinus” headed over to the group north of O’Neal Island and found it to include the J16s, J19s, and J39. These whales were grouped up tight and heading slowly north. Due to an annoying cloud that made things dark (“old man yells at cloud”) plus the whales weren’t arching much, just a few proof of presence shots were taken of this group at the time before moving back to the other group.\nBy 1520, the J14s, J17s, J22s, and L87 group had spread out into singles and small groups all heading slowly northwest. J22, J35, J37, and J40 were in a group together that rolled around a little as they moved in the direction of Spieden Island. J17 and J53 were traveling tightly together a couple of hundred yards behind the foursome. L87 was by himself a couple hundred yards to the north of J17 and J53. The other whales who had been part of the larger group were strung out and socializing several hundred yards behind J17 and J53.\nThe J16s and J19s group had passed Green Point by 1600 and were now traveling west on the north side of Spieden Island. This group had lost J39 but gained J27 and J31. Right before the Cactus Islands, these whales turned north and traveled slowly in a tight group back into Boundary Pass. The rest of J pod and L87 were about three quarters of a mile to the southeast of the J16s, J19s, and J11s and were still spread out in singles and small groups. There was a lot socializing going on in the trailing groups. J39 was actively going after J40 with L87 lingering nearby. J35 breached twice in a row. J38 was playing with some of the younger whales while bringing up the rear. The encounter ended at 1705 about a mile north of the east end of Johns Island with all the whales still heading slowly north in Boundary Pass.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-03-27"),
      sequence: 1,
      encounter_number: 24,
      start_time: "15:25",
      end_time: "18:05",
      vessel: "Morning Star",
      observers: "Melisa Pinnow, Jane Cogan, Tom Cogan",
      pods: "Transients",
      location_description: "Rosario Strait",
      start_lat: "48 33.938",
      start_long: "-122 45.356",
      end_lat: "48 31.170",
      end_long: "-122 46.305",
      summary: "On the morning of 27-Mar-19, whale watching boats found multiple groups of transient killer whales in the vicinity of Rosario Strait. As the day went on, all the groups eventually came together in the Thatcher Pass area of Rosario Strait. Melisa met Tom and Jane at Snug Harbor and left the dock at 1425 aboard “Morning Star”. At 1525, “Morning Star” arrived on scene in Rosario Strait with T46D, who was quickly heading north alone on the east side of Blakely Island. There were two more northbound groups about a quarter of a mile behind T46D, one closer to the middle of Rosario Strait (the T36Bs, T99s, and T137A), and another group farther to the west, closer to the Blakely Island shoreline (the T36As and T49As). Soon after, the T36As and T49As turned to the east, moving closer to the middle of the strait and the other group. The two groups then came together and stalled out to socialize. Many spy hops, aerial scans, half breaches, tail slaps, and pec slaps were observed. Some of the whales were also very tactile with each other.\n\nAt 1645, more whales were spotted to the south, east of Thatcher Pass. “Morning Star” headed that way and found the T46s (minus T46D) and T137s (minus T137A) all grouped up and slowly milling about, seemingly waiting for T46D and T137A to rejoin them. “Morning Star” stayed for a few surfacings before heading back to the big social group. The big social group had since split into three groups and fanned out. The T49As, T99B, and T99C were now heading slowly south as they continued to socialize while the T36As and T36Bs were still slowly heading north as they goofed off and playfully pushed T36B’s calf around at the surface. The third group was made up of T36, T99, T99D, and T137A and they had formed a resting line behind the T36As and T36Bs. Eventually T36, T99, T99D, and T137A turned south and the T36As and T36Bs slowly followed after them.\n\nBy 1730, all of the groups had trickled back into the same area outside of Thatcher Pass. The T46s had arrived from the east and T46D had apparently re-joined the rest of the family at some point. The T49As, T99B, and T99C arrived from the north first, then T36, T99, T99D, and T137A. The T36As and T36Bs brought up the rear and all the whales slowly meandered west toward to the entrance to Thatcher Pass. The T49As then split from the other whales and headed into Thatcher Pass. When this happened, the rest of the whales turned around and headed south in Rosario Strait, hugging the James Island shoreline as they went. The encounter ended at 1805.Photos taken under Be Whale Wise Guidelines"
    },
    {
      encounter_date: Date::strptime("2019-04-07"),
      sequence: 1,
      encounter_number: 25,
      start_time: "13:21",
      end_time: "16:24",
      vessel: "No Name",
      observers: "Ken Balcomb and Sabryna Bach",
      pods: "J Pod",
      location_description: "Admiralty Inlet",
      start_lat: "47 53.46",
      start_long: "-122 26.68",
      end_lat: "47 56.69",
      end_long: "-122 32.209",
      summary: "The day began with a plan to travel to Port Townshend by automobile to move our recently refurbished boat to a berthing slip at Point Hudson, strategically very near the Admiralty Inlet to Puget Sound. My very first encounter with J pod was in Admiralty Inlet in April 1976, long before their current popularity, and I hoped for a repeat of a pattern that we have observed with J pod traveling the waters of the Salish Sea in late winter/early spring. K and L pods mostly travel the coastal waters with occasional forays to inland waters when Chinook salmon migrate to their natal rivers to spawn. L pod was off the coast of central California last week, feeding upon Sacramento River Chinook salmon that were aggregating from Monterey to Half Moon Bay. K pod is yet to be located, but no doubt they are either looking for or finding salmon. I expected them all to potentially be coming this way any day soon. Unbeknown to me, J pod had slipped into the Admiralty Inlet during the previous afternoon/evening and in the morning was reported between Kingston and Edmonds, very spread out and not going anywhere. The salmon fishing for winter blackmouth (Chinook) had been pretty good lately, with most fish being 6-8 pounds and big ones up to 13 pounds, so I hoped to see if the whales were also getting in on the “bite”. My plan thus quickly changed from simply moving the boat to breaking in the new engine – running at various speeds for several hours, and attempting to encounter J pod for a quick check on J17. We left Point Hudson at 1220 and headed down the Inlet at various medium speeds, and encountered the first whale one hour later near the northwest edge of the Possession Point “Bar”. The whale, L87, and a fishing buddy that I took to be J49 were taking very long dives and travelling hundreds of yards up and down the Inlet, with gradual progress to the northwest. For half an hour, I saw no other whales before spotting another male fin briefly about a mile south of us. Long dives, changing directions, and brief no-saddle appearances at the surface were the pattern of the day for the whales for the next hour and a half – uneventful, except that a group that we found included J17, J44, J46, and J53, that I had hoped to see. J17 has improved and showed little sign of the “peanut-head” condition that had us very worried during an encounter with her on New Year’s Eve. At 1538, J42 appeared in the vicinity of this group, and gradually more whales began to show up spread out and travelling very slowly up the Inlet toward Double Bluff. By 1608, most of J pod was in an area of about six square miles in the middle of Admiralty Inlet, with many whales at the southerly end of the assemblage engaging in social contact and occasionally (and lazily) lobtailing as they moved gradually up the Inlet. A half a mile or so up the Inlet a few whales were also lazily lobtailing at the surface as they gradually moved down the Inlet. The assemblage gradually coalesced and then headed back down the Inlet toward the Possession Bar. After they surfaced and dove again, I checked out a few of the swirls of whale “tracks” looking for prey remains and scale samples, but saw none. A few small glittery specks were deep in the water column, and I presume any feeding was done near the bottom where blackmouth salmon are usually caught ten feet above the bottom in this region. We left the whales at 1624 as they headed back toward the Bar where the sport fishing fleet was working the incoming tide.On the morning of 8 April, 2019 J pod was observed heading up Haro Strait passing Lime Kiln lighthouse on San Juan Island as they continued their widely spread foraging expedition in the Salish Sea (the report of J pod in Puget Sound was sent to me by Alisa Lemire-Brooks). Judging by the time they spend in these inland marine waters, this habitat is a more important feeding area to them than it is to K or L pods that now rarely venture into the region. We will continue to keep track of all of the SRKWs that come into these core waters, and we also photo-document the Transient groups that now increasingly frequent the Salish Sea. Between Orca Network and their public sighting system, the marine naturalists of the Pacific Whale Watch Association, and our Center for Whale Research will document the whale distribution and condition in a changing world climate that will have a huge effect on the Pacific Northwest. Already, the effects are being felt with temperatures unfavorable to their salmon prey, and ocean acidification destroying the food chain due to excessive atmospheric CO2 from burning fossil fuels. These iconic animals are the canaries in the coal mine for the marine species that our life depends upon, and it is only common sense that we humans do whatever natural salmon recovery is necessary for their survival, rather than wasting money and concern over ephemeral noise issues and government agendas that are impossible to honestly evaluate. We absolutely know that SRKW survival is directly correlated with Chinook salmon abundance, and we also know that native wild salmon will ultimately provide the only path to salmon recovery. The only question is will we remove the dams blocking their natural lifecycle and restore habitats necessary for native salmon recovery,… before it is too late?Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-04-09"),
      sequence: 1,
      encounter_number: 26,
      start_time: "09:33",
      end_time: "10:16",
      vessel: "Mike 1",
      observers: "Mark Malleson",
      pods: "Bigg's Transients",
      location_description: "south of Kelp Reef",
      start_lat: "48 29.8",
      start_long: "-123 13.3",
      end_lat: "48 31.7",
      end_long: "-123 13.0",
      summary: "At ~0800 Hanna and I saw killer whales while having breakfast in Oak Bay between Chatham Island and the Chain Islands traveling north for Baynes Channel. We could see 1 bull that looked like T011A, a cow and what looked like a juvenile. At 0810 it looked as though they got a seal along the shoreline of Vantreight Island as I could see them milling about for several minutes with lots of gulls gathered around them.\nWe left the house as they exited Baynes channel to go to the boat. I left the Victoria Habour at 0850 and spotted them at 0930 a few miles south of Kelp Reef still traveling north. At the start of the encounter I saw them grab a likely seal and prey share while they continued to saunter north (48 29.8/123 13.3).\nI left them at 1016 3.5 miles south of Henry Island traveling slowly north against the ebb current (48 31.7/123 13.0).Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-04-21"),
      sequence: 1,
      encounter_number: 27,
      start_time: "13:00",
      end_time: "14:05",
      vessel: "Orcinus",
      observers: "Dave Ellifrit",
      pods: "J pod and L87",
      location_description: "Patos Island",
      start_lat: "48 46.42",
      start_long: "-122 58.42",
      end_lat: "48 47.43",
      end_long: "-123 00.80​",
      summary: "After receiving messages from Jane Cogan relaying reports of probable residents near Matia Island, Dave grabbed his gear, headed to Snug Harbor, and left in the boat around 1205. “Orcinus” arrived on scene near the west end of Patos Island at 1300 with the bulk of J pod in the lead group and the J16s about a half mile to the southwest of them. As the lead group rounded Alden Point in front of the Patos Island light station, they began to fan out and head northwest into the Strait of Georgia. A small group of juveniles including J46, J47, and J51 were socializing and rolling around together. The J16s also split up and spread out. Near the end of the encounter at 1405, many of the whales pointed west toward Tumbo Island and were reported to be milling in the same general area while “Orcinus” was on its way home.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-04-21"),
      sequence: 2,
      encounter_number: 28,
      start_time: "15:15",
      end_time: "16:00",
      vessel: "Orcinus",
      observers: "Dave Ellifrit",
      pods: "Transients",
      location_description: "San Juan Channel",
      start_lat: "48 34.46",
      start_long: "-123 03.80",
      end_lat: "48 33.54",
      end_long: "-123 01.27​",
      summary: "As “Orcinus” was heading home from the J pod encounter and nearing Roche Harbor and the fuel dock, word came over the radio that “Sea Lion” found a group of transients in San Juan Channel. That wasn’t very far away so Dave turned around and headed back out. “Orcinus” arrived on scene around 1515 about halfway between O’Neal Island and Pt. Caution. The T65As were heading southeast down San Juan Channel with four of them inshore in a tight group and T65A2 and T65A4 as the spread out outliers paralleling their course. As the group neared Pt. Caution, T65A2 and T65A4 surfaced from a long dive, milling, near Pt. Caution. The two groups merged and all six whales milled in the same area for the next fifteen minutes. The whales appeared to be feeding although there were no signs of what they killed and no gulls were gathering at the time. The encounter ended at 1600 near Pt. Caution with the T65As looking like they were just wrapping up their meal and beginning to continue down San Juan Channel.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-04-28"),
      sequence: 1,
      encounter_number: 29,
      start_time: "10:32",
      end_time: "11:35",
      vessel: "Mike 1",
      observers: "Mark Malleson, Hanna Magnusson",
      pods: "Transients",
      location_description:"South west of Constance Bank",
      start_lat: "48 17.6",
      start_long: "-123 23.7",
      end_lat: "48 17.1",
      end_long: "-123 20.8",
      summary: "At 0800 I received a report from a halibut fisherman that he had seen killer whales a few miles south of Trial Island (48 17/123 18) at ~0600. We departed Victoria harbour at 0900 and received a call that he resighted them in the same area and thought they may have been on a kill. We worked our way out towards the waypoints where he was anchored and spoke with him as we hadn't spotted them. He said he last saw them well to the south of him. We scanned with binoculars as we worked our way to the south west. We asked another halibut fisherman at anchor if he had seen any killer whales and he pointed us in the direction of Pedder Bay to the north west as he had seen them 20 minutes earlier. We then spotted them feeding in the distance as their was a large group of gulls hovering above them (48 17.6/123 23.7). T065A and T063 were slightly to the north west of the rest of the feeding group. They all milled around for a few minutes before they started to travel back to the south east towards where they were initially spotted with T063 and T065A .5nm to the north east of the group. We left them at 1135 as several commercial whale boats had arrived on scene (48 17.1/123 20.8).Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-04-28"),
      sequence: 2,
      encounter_number: 30,
      start_time: "14:15",
      end_time: "17:35",
      vessel: "Orcinus",
      observers: "Dave Ellifrit",
      pods: "J pod and L87",
      location_description: "Rosario Strait",
      start_lat: "48 38.52",
      start_long: "-122 45.02",
      end_lat: "48 38.06",
      end_long: "-122 36.02​",
      summary: "Ken called Dave a little before noon to relay a report that residents had been found near Matia Island. After a quick lunch, Dave grabbed his stuff and headed to Snug Harbor and left in the boat early in the afternoon. The whales had headed southeast towards Lawrence Point on Orcas Island and the leaders were just rounding the point when “Orcinus” arrived on scene around 1415. J pod and L87 were strung out in small groups over a half mile with most of them within a quarter mile of the Orcas Island shoreline. The whales moved offshore near the Peapod Rocks with most of the whales passing them on the east side. J pod then traveled slowly down Rosario Strait, loosely strung out, but still mostly in one group. By 1525, the whales were off of Peavine Pass when they took a hard right and headed inshore towards both Peavine and Obstruction Passes. Some whales spread out and seemed to be foraging along the Orcas Island while others socialized. The leaders moved slowly to the north over a half mile away from the trailers. The trailing group was a large group of socializing whales with a few foraging outliers. L87 made his way back out into the middle off Rosario Strait and was lost from sight although he could be heard blowing when the engine was off. The lead animals formed up into a group that included the J11s, J19s, and J22s. This group made it to about Doe Bay by 1655 before they turned around and headed back toward the trailers. The trailers, meanwhile, had picked up their pace and were heading towards leaders. The groups soon met up and, with the exception L87 and maybe another straggler or two, most of J pod headed slowly north together in a loose group. The encounter ended off Doe Bay at 1735.​Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-05-03"),
      sequence: 1,
      encounter_number: 31,
      start_time:1" 5:05",
      end_time: "18:20",
      vessel: "Orcinus",
      observers: "Dave Ellifrit",
      location_description: "SJ and New Channels",
      start_lat: "48 36.60",
      start_long: "-123 04.40",
      end_lat: "48 39.45",
      end_long: "-123 13.15​",
      summary: "Jane Cogan called Dave at home in the early afternoon to relay a report of a large group of transients heading northwest up San uanChannel. Dave grabbed his stuff and headed to Snug Harbor and left in the boat around 1440. “Orcinus” arrived on scene at 1505 about a mile and a half southwest of Jones Island. The T49As, T65Bs, T75Bs, T75Cs, and the T123s were in a single tight group traveling slowly northwest and appeared to be resting. The whales rested their way to the north side of Spieden Island and then all the way through New Channel. Once the whales exited New Channel, they briefly turned south before turning back west. The whales appeared to be waking up a little as there was some rolling and splashing that looked like socializing. The whales then turned north-northwest and headed up Haro Strait about a mile off the Stuart Island shoreline still in a tight group. The encounter ended at 1820 off of Tiptop Hill on Stuart Island.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-05-05"),
      sequence:1,
      encounter_number: 32,
      start_time: "14:45",
      end_time: "15:10",
      vessel: "Orcinus",
      observers: "Dave Ellifrit",
      pods: "Transients",
      location_description: "Beaumont Shoal",
      start_lat: "48 25.44",
      start_long: "-123 12.13",
      end_lat: "48 25.04",
      end_long: "-123 11.04​",
      summary: "Jane Cogan called Dave in the early afternoon to relay a report that T125A and T128 had been found near Beamont Shoal. Since they weren’t that far away, Dave grabbed his gear and headed for Snug Harbor and left in the boat at 1420. “Orcinus” arrived on scene around 1445 about halfway between the Beaumont Shoal buoy and Seabird Point on Discovery Island. T125A and T128 were spread out by at least a quarter mile with T125A being the whale to the west. T125A was milling in the same area briefly and T128 came over to the same area as T125A. However, when they came up again from a long dive, they had merely switched positions and now T128 was the west whale. T125A moved over a quarter mile away to the southeast of T128 but they were both traveling slowly south when the encounter ended at 1510 about a mile south of the Beaumont Shoal buoy.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-05-11"),
      sequence: 1,
      encounter_number: 33,
      start_time: "15:46",
      end_time: "16:37",
      vessel: "Mike 1",
      observers: "Mark Malleson, Hanna Magnusson",
      pods: "Transients",
      location_description: "Stuart Channel",
      start_lat: "48 55.1",
      start_long: "-123 39.2",
      end_lat: "48 54.1",
      end_long: "-123 37.3​",
      summary: "We departed Victoria harbour at 0855 on Mike 1 to look for killer whales. There was a large group of Transients reported south bound south of Nanaimo late afternoon the day before so we worked our way north up Haro Strait stopping at Turn Point for a good scan with the binoculars. We continued north east out Boundary Pass and stopped again at East Point for another scan before pushing out into the Strait of Georgia to a mile north east of Boiling Reef to get a better angle to scan the north east side of Patos Island and Alden Bank. As I scanned to the west back towards Tumbo Island I saw the back of a humpback whale. We worked our way back to the west and came across a pair of humpback whales (BCY0160/\"Heather\" and BCY00458/\"Raptor\") at 1055 (48 48.3/123 02.8). They were traveling tight together making less than 2 knots north west bound against the strong ebb current. They circled towards the shoreline of Tumbo Island and seemed to be feeding in the area.\nAt 1140 we received a report that a group of killer whales were spotted in Dodd's Narrows traveling south so we slowly worked our way in that direction via Boat Pass, Navy Channel and Trincomali Channel stopping and scanning on the way in case their were other killer whales around.\nWhen we got to the north west tip of Saltspring Island we turned south down Houstoun Passage and around the bottom of Kuper Island into Stuart Channel as we heard they were milling mid channel between Chemanius and Kuper Island.\nWe arrived at 1546 (48 55.1/123 39.2) to see the T123's a half mile to the west of the T086A's and both groups traveling slowly south bound. Within a few minutes the 086A's started to mill as if they had found a seal and the T123's soon joined them. They became quite animated for several minutes before they continued on their south bound track towards the north entrance of Sansum Narrows. We ended the encounter at 1637 (48 54.1/123 37.3).Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-05-14"),
      sequence: 1,
      encounter_number: 34,
      start_time: "14:35",
      end_time: "15:00",
      vessel: "Orcinus",
      observers: "Dave Ellifrit",
      pods: "Transients",
      location_description: "Spieden Island",
      start_lat: "48 38.59",
      start_long: "-123 10.31",
      end_lat: "48 39.29",
      end_long: "-123 11.40​",
      summary: "Dave received several calls from various sources about a couple of different groups of Bigg’s killer whales in the area, including a group that headed up San Juan Channel and into Spieden Channel. As the San Juan Channel whales neared the west end of Spieden Channel, reports said that T87 and the T90s were present but there was still a little confusion about who a couple/few extras were in the group. Dave grabbed his gear, headed for Snug Harbor, and left in the boat at 1415.\n“Orcinus” arrived on scene around 1435 off the west end of Spieden Island. The whales were just finishing feeding after a kill and blubber oil could be smelled in the air. A group of five or six whales were grouping up while another pair of whales were still feeding about 200 yards to the east of them. After a long dive, all the whales formed up in a tight group heading towards, and then along, the southwestern tip of Stuart Island. The other matriline in the group with T87 and the T90s turned out to be the T124A2s. The encounter ended at 1500 with the whales continuing slowly northwest up the southwestern shoreline of Stuart Island.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-05-17"),
      sequence: 1,
      encounter_number: 35,
      start_time: "12:09",
      end_time: "13:05",
      vessel: "Mike 1",
      observers: "Mark Malleson",
      pods: "Transients",
      location_description: "Race Rocks",
      start_lat: "48 18.9",
      start_long: "-123 31.6",
      end_lat: "48 18.1",
      end_long: "-123 29.1",
      summary: "I left Victoria harbour at 1130 to follow up a report of 2 bulls headed north near Race Rocks.\nI came across T093 and T097 west bound east of Race Pass. As they were heading west through Race Pass I received a call that Mirauder IV had spotted a group of females and juveniles with a newish calf ~ 2 miles to the east. I left immediately as they were pressed for time and the conditions weren't ideal for keeping track of them. The wind was blowing close to 20 knots from the south west. I was able to confirm members of the T046B’s. They were pointed south but doing long dives making it hard to photograph in the rough seas. There was a newish calf in the group that was quite scarred up and light grey in colour that appeared to be with T046B1 who was seen with a calf last fall. I saw a second newer calf that was with T046B. I ended the encounter at 1305.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-05-31"),
      sequence: 1,
      encounter_number: 36,
      start_time: "10:45",
      end_time: "11:50",
      vessel: "Orcinus",
      observers: "David Ellifrit, Michael Weiss, Darren Croft",
      pods: "Transients",
      location_description: "Beaumont Shoal, Haro Strait",
      start_lat: "48 28.46",
      start_long: "-123 12.23",
      end_lat: "48 29.17",
      end_long: "-123 11.01​",
      summary: "Dave, Michael, and Darren left Snug Harbor on Orcinus at 1030. There had been reports of a group of Transients near Beaumont Shoal, so the team headed across Haro Strait in that direction.\n\nThe team arrived on scene north of Beaumont Shoal, to find the T65Bs, T75Bs, and T75Cs (8 whales in total). The whales were in tight groups, being extremely social. The younger whales were constantly playing, with lots of spy hops and breaches.\n\nThe group slowly made their way northwest towards San Juan Island, with the adults in the lead and the young individuals following. The group continued to socialize as the team left the scene just before 1200.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-06-12"),
      sequence: 1,
      encounter_number: 37,
      start_time: "14;21",
      end_time: "16:18",
      vessel: "Chimo",
      observers: "Ken Balcomb and Sabryna Bach",
      pods: "T77s",
      location_description: "Port Angeles Harbor",
      start_lat: "48 08.814",
      start_long: "-123 24.025",
      end_lat: "48 07.652",
      end_long: "-123 27.27",
      summary: "The Bigg's Transient killer whales were reported in the morning about six miles south of Otter Point, Canada, and they gradually travelled eastward toward Port Angeles. Several PWWA vessels were in the vicinity and they tentatively identified the group of five whales to be the T77s. As the whales approached Ediz Hook, we launched in Chimo shortly after 2PM to obtain confirming photographs of them and confirmed that T77 and T77B were indeed in the group, along with three others that are presumed to also be T77s, but with new markings not in our catalog dated 2016. It is time for a new catalog and Jared Towers of DFO is coming out with one next week. We will update ours later. To everyone's amazement the whales calmly spread out and went far into Port Angeles Harbor to right off the paper mill and Boat Haven entrance before turning and heading back out of the harbor. After rounding Ediz Hook, they headed back west in the Strait of Juan de Fuca.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-06-20"),
      sequence: 1,
      encounter_number: 38,
      start_time: "12:50",
      end_time: "14:30",
      vessel: "Orcinus",
      observers: "David Ellifrit, Michael Weiss, Katie Jones",
      pods: "Transients",
      location_description: "Haro Strait",
      start_lat: "48 28.4",
      start_long: "-123 6.46",
      end_lat: "48 38.6",
      end_long: "-123 10.25​",
      summary: "There had been reports of multiple groups of transient killer whales around San Juan Island in the morning, so around noon Dave, Michael, and Katie met at Snug to document them. They headed south along the west side of the island, and arrived on scene off False Bay with the T124As. The whales were fairly spread out and travelling north. After a quick look, Dave identified T86A1 in the group as well, but did not see T123A3 and her calf, or T124A4. After a single quick ID photo pass, the team headed north up the strait, where they encountered the T65As about a mile east of Sydney Island. The whales were zig-zagging and apparently socializing after having made a kill earlier in the day. The team stayed for a couple surfacing sequences and made sure that the whole group was present. Reports over the radio indicated that there were whales inshore of the southern group that may have been the missing whales from the previous passes. The team headed southwest and waited for the group north of Lime Kiln. Soon, the group came travelling north, keeping close to the shoreline, still steadily travelling and spread out. After a few surfacing sequences, the team did get ID shots of T124A3, T124A3A, and T124A4. At 1430, the team ended the encounter, although there was word on the radio that there was another group of whales nearby, other than the whales that had already been documented.​Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-06-26"),
      sequence: 1,
      encounter_number: 39,
      start_time: "10:50",
      end_time: "12:15",
      vessel: "Orcinus",
      observers: "David Ellifrit, Michael Weiss",
      pods: "Transients",
      location_description: "Haro Strait",
      start_lat: "48 32.12",
      start_long: "-123 13.28",
      end_lat: "48 29.48",
      end_long: "-123 11.12​",
      summary: "Michael received a report from Jane Cogan about transient calls on Haro Strait hydrophones, and later visual confirmation of a group of whales in mid Haro headed towards Kelp Reef. At 1030, Dave and Michael left Snug to try to locate and ID the whales. At 1050, they arrived on scene southwest of Kelp Reef with the T46Bs, T36As, T65Bs, and T77A. The whales were socializing, and milling non-directionally. At 1130, the whales split into two groups. The T36As, T65Bs, and T77A headed northwest, moving quickly, with T77A separated from the rest of the group by nearly a mile. The T46Bs, meanwhile, headed south down Haro Strait. The team spent a bit of time trying to keep up with the northern group, before flipping to get more photos of the T46Bs, particularly interested in further assessing T46B1B’s skin condition. At 1215, the team ended the encounter in mid Haro Strait, just west of Lime Kiln park.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
    {
      encounter_date: Date::strptime("2019-06-29"),
      sequence: 1,
      encounter_number: 40,
      start_time: "17:40",
      end_time: "18:05",
      vessel: "Mike 1",
      observers: "Mark Malleson and Dave Ellifrit",
      pods: "Transients",
      location_description: "Cape Flattery",
      start_lat: "48 25.07",
      start_long: "-124 40.57",
      end_lat: "48 25.20",
      end_long: "-124 38.12​",
      summary: "Mark and Dave did a survey on Saturday all the way out the Strait of Juan de Fuca and past Carmanah Point. We checked out a couple of corners of Swiftsure Bank and found some scattered humpbacks but no killer whales. On our way back in from the bank, Mark spotted some blows a couple miles to the northeast of Cape Flattery. The whales turned out to be the T37As heading east in the Strait of Juan de Fuca. The T37As traveled in a tight group with a newish calf tight by T37A's side. The calf did briefly travel between a pair of siblings before returning to T37A’s side. We stayed with the group for 25 minutes and left them still traveling in an easterly direction at 1805.Photos taken under Federal PermitsNMFS PERMIT: 21238/ DFO SARA 388"
    },
]
